# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name : Bhoomi-1


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: S3Upload@1
  inputs:
    awsCredentials: 'Demo-devops-aws-connection'
    regionName: 'ap-south-1'
    bucketName: 'myy-demo-s3'
    globExpressions: '*'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
